# Generated by Django 3.1 on 2020-08-23 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0002_auto_20200823_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.URLField(default='default', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rental_Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=2000)),
                ('picture', models.URLField()),
                ('link', models.URLField()),
                ('available', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('replacement_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals_app.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals_app.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals_app.profile')),
            ],
        ),
    ]
