# Generated by Django 3.1 on 2020-08-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0003_auto_20200823_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.URLField(default='https://images.unsplash.com/photo-1506551109886-6101f48c1ab9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80', max_length=500),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='picture',
            field=models.URLField(default='https://images.unsplash.com/photo-1557318041-1ce374d55ebf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80'),
        ),
    ]
