# Generated by Django 3.1 on 2020-08-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0005_auto_20200823_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='default', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(max_length=50, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='link',
            field=models.URLField(blank=True, verbose_name='Link To Producte Page'),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='picture',
            field=models.URLField(blank=True, verbose_name='Picture (URL)'),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price Per Day'),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='replacement_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Replacement Value'),
        ),
    ]
