# Generated by Django 3.1 on 2020-08-24 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0006_auto_20200823_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pick_up', models.DateTimeField()),
                ('drop_off', models.DateTimeField()),
                ('picked_up', models.BooleanField(blank=True)),
                ('returned_date', models.DateTimeField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals_app.rental_item')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals_app.profile')),
            ],
        ),
    ]
