# Generated by Django 3.1 on 2020-08-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0007_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
