# Generated by Django 3.1 on 2020-08-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0008_auto_20200824_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
    ]
