# Generated by Django 3.1 on 2020-08-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0009_reservation_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
