# Generated by Django 3.1 on 2020-08-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0011_auto_20200824_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='drop_off',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Choose a drop off day and time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='pick_up',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Choose a pick up day and time'),
        ),
    ]
