# Generated by Django 3.1 on 2020-08-27 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0012_auto_20200825_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='picked_up',
            field=models.BooleanField(default=False),
        ),
    ]
