# Generated by Django 3.1 on 2020-08-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0014_rental_item_min_rental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_item',
            name='min_rental',
            field=models.IntegerField(default=1, verbose_name='Minimum Rental Period'),
        ),
    ]
