# Generated by Django 3.1 on 2020-08-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals_app', '0015_auto_20200827_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ready_for_pickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rental_item',
            name='min_rental',
            field=models.IntegerField(default=1, verbose_name='Minimum Rental Period in Days'),
        ),
    ]
